---
qdts_version: 0.1.0
config:
  application_interface: etsi-gs-qkd-004
  qkd_protocol: e91
nodes:
  - node_name: munich
    node_ip: 10.4.16.115
    neighbour_nodes:
      - salzburg
      - nuremberg
  - node_name: nuremberg
    node_ip: 10.4.16.74
    neighbour_nodes:
      - salzburg
      - munich
  - node_name: salzburg
    node_ip: 10.4.16.132
    neighbour_nodes:
      - munich
      - nuremberg
  